# Generated by Django 2.2 on 2019-04-17 22:11

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fts_regconfig', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('terms', django.contrib.postgres.search.SearchVectorField(blank=True)),
                ('publish_after', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_username', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by_username', models.CharField(max_length=120)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('published_by_username', models.CharField(blank=True, max_length=120, null=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posts', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(default='en-us', on_delete=django.db.models.deletion.PROTECT, to='blogitor.Language')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_posts', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
