# Generated by Django 2.2 on 2019-04-17 22:28

import blogitor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='importance',
            field=models.IntegerField(choices=[(blogitor.models.Importance(-1), 'low'), (blogitor.models.Importance(0), 'normal'), (blogitor.models.Importance(1), 'high'), (blogitor.models.Importance(10), 'critical')], default=blogitor.models.Importance(0)),
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.ForeignKey(default='pl', on_delete=django.db.models.deletion.PROTECT, to='blogitor.Language'),
        ),
    ]
